export const clientsIndustry = [
  'AI and Machine Learning',
  'Augmented Reality',
  'Blockchain',
  'CRM software',
  'Cybersecurity',
  'Data Science',
  'Digital design',
  'E-commerce, Education, Health and Fitness, Lifestyle',
  'Ecommerce',
  'eLearning',
  'ERP software',
  'eWallet Platform Provider',
  'Fintech',
  'Game Development',
  'HR Software',
  'Live Chat software',
  'Logistics',
  'Marketplaces',
  'Martech (Marketing Tech)',
  'Mobile Development',
  'NFT Marketplace',
  'Payment Gateway Provider',
  'Point of sale software',
  'Project Management software',
  'Real Estate',
  'SaaS',
  'Sport Activity',
  'Telecom',
  'Video (Face) recognition',
  'Voice recognition',
  'Webinar software'
];

export const codeLanguage = [
  '.NET3',
  '.Net Core',
  'Adobe After Effect',
  'Adobe Illustrator',
  'Adobe Photoshop',
  'Ajax',
  'Android',
  'Angular',
  'Apache',
  'ArgoCD',
  'Autoencoders',
  'AWS',
  'Backend development',
  'Blackbox testing',
  'Blockchain',
  'Bootstrap',
  'C / C++ / Embedded',
  'Chai',
  'CI/CD - Github',
  'CNN',
  'Coldfusion',
  'Data Science',
  'DevOps / Sysadmin',
  'Django',
  'DNN',
  'Docker',
  'Drone CI',
  'ELK',
  'Express.js',
  'Facebook SDK',
  'Figma',
  'Firebase',
  'Flask',
  'Flutter',
  'Flux',
  'Front-end / JavaScript',
  'Frontend development',
  'Full Stack Development',
  'Gamedev / Unity / AS3',
  'GAN',
  'Gitlab',
  'Grafana',
  'Invision',
  'ionic',
  'iOS',
  'IT Consulting',
  'J2EE',
  'Java',
  'Javascript',
  'Jenkins',
  'Jira',
  'jQuery',
  'Koa 2',
  'Kotlin',
  'Kubernetes',
  'Laravel',
  'LSTM',
  'Magento',
  'Marvel',
  'Meteor.js',
  'MongoDB',
  'MS Azure services',
  'MySQL',
  'Next.js',
  'Node.js',
  'Nuxt.js,',
  'Objective-C',
  'Opencart',
  'PHP',
  'PostgreSQL',
  'Prometheus',
  'Python',
  'Pytorch',
  'QA Automation',
  'R',
  'React Native',
  'Redis',
  'Redux',
  'Redux-Saga',
  'Reselect',
  'ROR',
  'Ruby / Rails',
  'Rust',
  'Scala',
  'Shopify',
  'Smoke testing',
  'solidity',
  'Substrate',
  'Swagger',
  'Swift',
  'TensorFlow',
  'Unity',
  'UX / Design',
  'vue.js',
  'Web3',
  'Woocommerce',
  'WordPress',
  'Zend'
];

export const companyType = [
  'Customizer',
  'Ecosystem provider',
  'Outsourcing software development',
  'Product company',
  'R&D Center',
  'SaaS',
  'Startup'
];
