export type CompanyListData = {
   company_name: string,
   logo: string,
   website: string,
   tagline: string,
   client_industry: string,
   software_stack: string,
   industry_choice: string,
   short_description: string,
   full_description: string,
   average_hourly_rate: number,
   currency_rate: string,
   minimum_project_budget: number,
   currency_budget: number,
   team_size: number,
   location: string,
   foundation_date: string,
   clients_focus: string,
   contact_marketing: string,
   contact_expert: string,
   links_case: string,
   client_describe: string,
   employees: [],
   owner: null
}